//! 构建脚本。
//!
//! **为什么需要 app_manifest**：面板（= 远端 origin `http://127.0.0.1:<port>`）要通过 IPC 调
//! 自定义命令，而 `tauri-2.12.1/src/webview/mod.rs` 的注释写明：
//!
//! > Check ACL on plugin commands, when the app defined its ACL manifest,
//! > or when the request comes from a non-local (remote) origin. This ensures remote
//! > content can never reach custom commands unless an explicit `remote` capability
//! > has been configured for them.
//!
//! 也就是说：来自远端 origin 的 IPC 请求**一律走 ACL 检查**。
//!
//! ## 为什么这里漏一条命令会出两种事故
//!
//! `AppManifest::commands()` 里声明的名字（**snake_case 的命令名**）会生成权限文件
//! `permissions/autogenerated/<command>.toml`，其中的 **identifier 是 kebab-case**：
//! `tauri-utils/src/acl/build.rs` 原文 `let slugified_command = command.replace(_,"-")` →
//! `identifier = "allow-shell-get-settings"`。据此漏声明的后果分两种：
//!   1. 命令没进清单 → `tauri-macros/src/command/handler.rs:41,92` 的 `filter_unused_commands`
//!      把它从 handler 里**删掉** → 面板只看到 “Command not found”（静默）；
//!   2. capability 里引用了不存在的 `allow-xxx` → `RuntimeAuthority::add_capability_inner`
//!      对 `resolve_with_base_scope_id(...)` 直接 `.unwrap()` → **启动 panic**。
//!
//! 所以此处与 `capabilities/` 必须同时成立，改动时两边一起改。

fn main() {
    let _ = tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                // 更新器（updater 模块）
                "shell_check_update",
                "shell_download_update",
                "shell_cancel_download",
                "shell_install_update",
                "shell_ignore_version",
                // 设置读写（shell 模块）——命令名以 shell 模块最终实现为准，缺了在这里补
                "shell_get_settings",
                "shell_set_settings",
                "shell_context_menu",
            ]),
        ),
    );
}
